#!/usr/bin/env bash

set -eux -o pipefail
-e immediately exit if any command [1] has a non-zero exit status
-x all executed commands are printed to the terminal
-u When set, a reference to any variable you haven't previously defined - with the exceptions of $* and $@
-o pipefail This setting prevents errors in a pipeline from being masked

for i in {1..3}; do
  echo ${i}
done


while true; do
  sleep 1
done


VARIABLE="see"
echo 'Variable is expanded '${VARIABLE}''

if [ -z $VARIABLE ]; do
  echo "True if the length of STRING is zero"
fi

FIRST_ARG="${1:-default}"
