services:
  api:
    image: 'nginx:latest'
    ports:
      - '8080:80'
    resources:
      limits:
        cpus: '0.10'
        memory: 128M
      reservations:
        cpus: '0.10'
        memory: 128M
